var AI_MANGA_UPSCALER_CONFIG = Object.freeze({
  backend: {
    baseUrl: "http://127.0.0.1:8766",
    requiredPipelineVersion: "4",
    requestTimeoutMs: 20000,
    defaultProcessingTimeoutSeconds: 60,
  },
  cache: {
    memoryMaxEntries: 64,
    indexedDbName: "ai-manga-upscaler-cache",
    indexedDbStoreName: "images",
    indexedDbMaxEntries: 500,
  },
  images: {
    browserReadTimeoutMs: 15000,
    minWidthPx: 300,
    minHeightPx: 300,
    maxWidthPx: 8000,
    maxHeightPx: 12000,
    maxOutputWidthPx: 2048,
    maxOutputHeightPx: 8192,
    slicingEnabled: true,
    sliceMaxWidthPx: 8192,
    sliceMaxHeightPx: 2200,
    outputQuality: 90,
    prefetchMarginPx: 1800,
    cancelDistancePx: 3600,
    aheadProcessingEnabled: true,
    aheadProcessingImageLimit: 3,
    preprocessingQueueTimeoutMs: 30000,
    sliceDecodeTimeoutMs: 10000,
    sliceCropTimeoutMs: 15000,
    sliceEncodeTimeoutMs: 10000,
    sliceLoadTimeoutMs: 15000,
    sliceFingerprintTimeoutMs: 10000,
    segmentEnqueueTimeoutMs: 10000,
  },
  queue: {
    preprocessingConcurrency: 3,
    maxConcurrentRequests: 2,
  },
  render: {
    fadeMs: 180,
  },
  retry: {
    maxAttempts: 3,
    baseDelayMs: 750,
  },
  enhancement: {
    defaultMode: "auto",
    defaultLevel: 0.35,
    modes: ["auto", "manga", "artwork", "photo"],
  },
  text: {
    cleanupEnabled: false,
    translateEnabled: false,
    sourceLanguage: "auto",
    targetLanguage: "vi",
  },
});
